# Generated by Django 3.2.9 on 2021-11-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy_dev_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='content',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='guide',
            name='likes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='guide',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
