# Generated by Django 3.2.9 on 2021-11-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy_dev_api', '0002_auto_20211119_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
