# Generated by Django 3.2.9 on 2021-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy_dev_api', '0003_alter_guide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
