# Generated by Django 3.2.9 on 2021-11-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy_dev_api', '0004_auto_20211119_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='content',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
