# Generated by Django 3.2.9 on 2021-11-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazy_dev_api', '0006_auto_20211119_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='imageFile',
        ),
    ]
